name: Vercel Production Deployment

env:
  vercel_token: ${{ secrets.VERCEL_TOKEN1 }}
  vercel_project_name: "News" # Replace with your Vercel project name
  vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }} # Optional

on:
  push:
    branches:
      - main # Trigger deployment on push to the 'main' branch

jobs:
  frontend:
    name: Frontend Deployment to Vercel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN1 }}

      - name: Build project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN1 }}

      - name: Deploy Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN1 }}
